spring:
  application:
    name: matrix-158-spring-practice-app

  datasource:
    url: jdbc:mysql://localhost/mj_course_management
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false


#  liquibase:
#    change-log: classpath:/db/changelog/db.changelog-master.yaml
#    enabled: true


